plugins: rubocop-performance

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - spec/parsing_tests/*
    - vendor/**/*
    - benchmarks/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundOperators:
  EnforcedStyleForExponentOperator: space

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Style/SignalException:
  Exclude:
    - spec/**/*

Naming/PredicateMethod:
  Exclude:
    - lib/minicss/css/parser.rb

Lint/HashCompareByIdentity:
  Exclude:
    - lib/minicss/sel.rb

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
